### ISSUE TITLE
ImportError: No module named 'aiohttp.wsgi'

### ISSUE THREAD

**Issue by eddyekofo94** [housleyjk/aiopyramid#31] opened 2017-05-05 08:07 UTC
```
Error: class uri 'aiopyramid.gunicorn.worker.AsyncGunicornWorker' invalid or not found:
 
[Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/gunicorn/util.py", line 134, in load_class
    mod = import_module('.'.join(components))
  File "/usr/lib64/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed

  File "/usr/lib/python3.5/site-packages/aiopyramid/gunicorn/worker.py", line 7, in <module>
    from gunicorn.workers.gaiohttp import AiohttpWorker
  File "/usr/lib/python3.5/site-packages/gunicorn/workers/gaiohttp.py", line 14, in <module>
    from gunicorn.workers._gaiohttp import AiohttpWorker
  File "/usr/lib/python3.5/site-packages/gunicorn/workers/_gaiohttp.py", line 19, in <module>
    from aiohttp.wsgi import WSGIServerHttpProtocol as OldWSGIServerHttpProtocol
ImportError: No module named 'aiohttp.wsgi'
]
```
according to this http://aiohttp.readthedocs.io/en/stable/migration.html#wsgi it has been dropred, how can I work arounf this?

**Comment by housleyjk** [comment] 2017-05-07 18:44
dupe of #30, I will publish a change that locks the version.

**Closed by housleyjk** 2017-05-07 18:44 UTC
