### ISSUE TITLE
aiopyramid braking pyramid_jwtauth

### ISSUE THREAD

**Issue by riccardocagnasso** [housleyjk/aiopyramid#14] opened 2015-11-26 17:51 UTC
Hi, i was testin your aiopyramid in a project of mine. It went like a breeze except for the fact that it broke my authentication setup based on jwtauth.

I would really like to provide more informations but i'm unsure how. As soon as i switch to aiopyramid.gunicorn.worker.AsyncGunicornWorker i get 403 on secured pages even tough i'm providing the correct JWT token.

**Comment by housleyjk** [comment] 2015-11-27 06:26
How big is your project? Can you send me a minimal site that replicates the issue? If you can't send me a complete mini project, please paste a clean development.ini and a sample view that is failing. In order to know why it's failing, we probably need to learn at what stage the authentication is failing. At least you are getting a 403! That should mean that your system at least starts to verify the web token, right?

**Comment by riccardocagnasso** [comment] 2015-11-27 12:33
> At least you are getting a 403! That should mean that your system at least starts to verify the web token, right?

I beg to differ. I'm no pyramid internals ninja, but authentication and authorization are separated in pyramid, the 403 results from a test in the authentication that fails because authentication doens't work and so there's no logged in user. AFAIK pyramid_jwtauth doesn't provides an Authentication interface but no Authorization facility at all.

I made some empirical tests and i believe - but i couldn't swear on that - the Authentication passage is skipped at all.

> Can you send me a minimal site that replicates the issue? 

Yes Sir, i can. https://github.com/riccardocagnasso/jwtauth_aiopyramid_test
Just clone it, run python setup.py develop in a proper virtualenv and note that with development.ini (that uses aiopyramid.gunicorn.worker.AsyncGunicornWorker) the authorization won't work while with  development-noasync.ini (that uses waitress) it will.

Please note that i created and tested this with Python 3.5.

**Comment by housleyjk** [comment] 2015-11-27 19:27
Ok, I found your bug. It's in the `aiohttp` library: `aiohttp.wsgi:69` in `create_wsgi_environ` the Authorization header is being filtered out. If you remove that code, your testing miniproject works. Please take up the issue with `aiohttp` and good luck with your project! Let me know if you need more help.

**Comment by housleyjk** [comment] 2015-11-27 19:27
In the meantime, you may be able to get your library running on uwsgi until the issue is fixed with aiohttp.

**Closed by housleyjk** 2015-11-27 19:27 UTC

**Comment by riccardocagnasso** [comment] 2015-11-28 12:05
Thx, i opened a ticket on their trac.

Here, if you want to follow it https://github.com/KeepSafe/aiohttp/issues/648
